/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package progettorubricaturingmod;

import static java.awt.image.ImageObserver.HEIGHT;
import javax.swing.JOptionPane;

/**
 *
 * @author simdr
 */
public class FinestraEditorPersona extends javax.swing.JFrame {

    FinestraPrincipale finestraPrincipale;

    Persona personaDaModificare;

    /**
     * Creates new form FinestraNuovaPersona
     *
     * @param finestraPrincipale
     * @param personaDaModificare
     */
    public FinestraEditorPersona(FinestraPrincipale finestraPrincipale, Persona personaDaModificare) {
        this.finestraPrincipale = finestraPrincipale;
        this.personaDaModificare = personaDaModificare;

        initComponents();

        if (this.personaDaModificare != null) {
            nomeTextField.setText(personaDaModificare.getNome());
            cognomeTextField.setText(personaDaModificare.getCognome());
            indirizzoTextField.setText(personaDaModificare.getIndirizzo());
            telefonoTextField.setText(personaDaModificare.getTelefono());
            etaTextField.setText(String.valueOf(personaDaModificare.getEta()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nomeTextField = new javax.swing.JTextField();
        cognomeTextField = new javax.swing.JTextField();
        indirizzoTextField = new javax.swing.JTextField();
        telefonoTextField = new javax.swing.JTextField();
        etaTextField = new javax.swing.JTextField();
        jToolBar1 = new javax.swing.JToolBar();
        bottoneSalva = new javax.swing.JButton();
        AnnullaBottone = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Finestra Editor Persona");
        setLocation(new java.awt.Point(400, 0));

        jLabel1.setText("Nome");

        jLabel2.setText("Cognome");

        jLabel3.setText("Indirizzo");

        jLabel4.setText("Telefono");

        jLabel5.setText("Età");

        jToolBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setRollover(true);

        bottoneSalva.setText("Salva");
        bottoneSalva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottoneSalvaActionPerformed(evt);
            }
        });
        jToolBar1.add(bottoneSalva);

        AnnullaBottone.setText("Annulla");
        AnnullaBottone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnullaBottoneActionPerformed(evt);
            }
        });
        jToolBar1.add(AnnullaBottone);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cognomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(indirizzoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefonoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nomeTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cognomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(indirizzoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(telefonoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(etaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bottoneSalvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottoneSalvaActionPerformed
        String nomeInserito = nomeTextField.getText();
        String cognomeInserito = cognomeTextField.getText();
        String indirizzoInserito = indirizzoTextField.getText();
        String telefonoInserito = telefonoTextField.getText();
        String etaInserito = etaTextField.getText();

        if (nomeInserito.equals("") || cognomeInserito.equals("") || indirizzoInserito.equals("") || telefonoInserito.equals("") || etaInserito.equals("")) {
            System.out.println("Ci sono dei campi vuoti.");
            JOptionPane.showMessageDialog(this, "Compila tutti i campi.", "Errore", HEIGHT);
        } else {
            try {
                int etaInseritoInt = Integer.parseInt(etaInserito);

                Persona nuovaPersona = new Persona(nomeInserito, cognomeInserito, indirizzoInserito, telefonoInserito, etaInseritoInt);

                if (personaDaModificare != null) {
                    finestraPrincipale.modificaPersonaArrayList(personaDaModificare, nuovaPersona);

                    //finestraPrincipale.rimuoviModificaPersonaFileInformazioni(personaDaModificare, nuovaPersona, null, null, null);
                    finestraPrincipale.rimuoviModificaPersonaCartellaInformazioni(personaDaModificare, nuovaPersona, null, null, null);
                
                } else {
                    finestraPrincipale.aggiungiPersonaArrayList(nuovaPersona);

                    //finestraPrincipale.creaFilePersonaCartellaInformazioni(nuovaPersona);
                    finestraPrincipale.aggiungiFilePersonaCartellaInformazioni(nuovaPersona);
                }

                finestraPrincipale.popolaTabella();

                this.dispose();

            } catch (NumberFormatException e) {
                System.out.println("L'età inserita non è un numero intero.");
                JOptionPane.showMessageDialog(this, "Inserisci un numero intero positivo nel campo età.", "Errore", HEIGHT);
            }

        }
    }//GEN-LAST:event_bottoneSalvaActionPerformed

    private void AnnullaBottoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnullaBottoneActionPerformed
        this.dispose();
    }//GEN-LAST:event_AnnullaBottoneActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnnullaBottone;
    private javax.swing.JButton bottoneSalva;
    private javax.swing.JTextField cognomeTextField;
    private javax.swing.JTextField etaTextField;
    private javax.swing.JTextField indirizzoTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JTextField telefonoTextField;
    // End of variables declaration//GEN-END:variables
}
